### ISSUE TITLE
List of (?) Bugs!

### ISSUE THREAD

**Issue by bobmuscarella** [ndimhypervol/wallace#46] opened 2015-08-31 04:00 UTC
Overall, really nice work!  I'll cut to the chase and get to the things that didn't work for me.  I've separated the bugs I found into ones that caused crashes and more stylistic points (but I think still important).  They are (roughly) in order of operations... let me know if i can clarify anything...

**Crash bugs**

1. There is a fatal error when trying to change the buffer size with the MCP option for defining environmental bounding box.  Details: I put 10 in the box and then tried to change it to 5 but it wouldn’t change the size of the polygon.  I pressed ‘enter’ and the screen froze.  The R studio session had a popup box saying, 
`R encountered a fatal error.  R session Aborted`
I restarted the app and the same thing happened.  I avoided it only by not changing my buffer box size or by selecting a different buffer option checkbox in between changing the size.

2. If you DON’T hit the “Mask Predictors by Background”, in the ‘Processing Env Data’ tab, Wallace crashes when trying to do spatial partitions.  You get this warning in the R session:
`Warning: Unhandled error in observer: unable to find an inherited method for function ‘nlayers’ for signature ‘"NULL"
observeEvent(input$goPart)`
This happened to me a few times because I forgot to hit that button.  That is related to the issue below that the label of that button is not very intuitive.  It could be changed and there could be a warning if the user proceeds without clipping the environmental data...

3. Error when running ENMeval.  In numerous attempts to run ENMeval, the screen greyed out and i wasn’t sure if it crashed or if it was running.  I tried with different options but it always happened. The R session showed the following warning:
`Warning: Unhandled error in observer: unused argument (updateProgress = updateProgress)
observeEvent(input$goEval)`
Even when I only selected “L” and RM 1 it crashed.

4. There was a crash when I tried to do “Plot Prediction” after a BioClim run (I never made it to "plot prediction" of ENMeval run because of the previous issue).  The R session warning was:
`Warning: Unhandled error in observer: trying to get slot "predictions" from an object of a basic class ("NULL") with no slots
observeEvent(input$plotPred)`
So, I never got it to show me mapped predictions.

**Style bugs**

1. Map window and page layout:
  - Can the map window be slightly smaller?  The stuff below the map (e.g., detailed occurrence point data in the ‘process occ’ tab) isn’t obvious unless you scroll down on the page… A slightly smaller map may make this more immediately visible…

2. On the “(Obtain Occ Data)” tab, loading occurrence records from GBIF works but if you click the button for download .csv before hitting “search GBIF” you get sent to an error page that says, `cannot coerce class "gbif" to a data.frame`.  Can there be an error trap here that gives a message saying something like `Need to acquire GBIF points first.  Search GBIF for a species`

3. Manual (polygon) selection of occurrence points:
  - I had a hard time figuring out how to get this to work.  The description of how to make the polygons could be more clear.  
 - You cannot put polygon points inside of a polygon you already drew.  So, if you mess up in drawing one polygon, you have to clear them and start over... kind of clunky.
 - I didn’t realize you click in multiple places to draw the vertices of the polygon.  Also, did the ability to delete by point ID number go away?  That would be cool to have additionally, if possible...

4. Map legend (a few suggestions):
 - In all cases, move the legends to the top (right or left) corner.  I had to scroll down to see it and so it is not immediately obvious what the different colored points meant.
 - Change the words in the legends.  It could be more explicit that red “thinned” points are ones that were removed or excluded.  (I initially thought ‘thinned’ referred to the remaining ‘thinned’ points).  “current” wasn’t totally clear, either (not the opposite of ‘thinned’).  I recommend changing these to ‘excluded’ and ‘included’ (or, ‘omitted’ and ‘retained’).
 - The legend on the ‘Obtain Env Data’ tab only seems to have a red square with ‘current’ label.  What happened to the blue and yellow labels?  These are missing but should probably be included.

5. The text on the button “Mask Predictors by Background” is confusing.  What is the background here?  Shouldn’t it be polygon or box or something like that?  This is also related to **Crash Bugs** number 2.

6. there is text on the BioClim Module that says, “BIOCLIM STUFF”… I guess that is Rob’s text?  This just needs to be changed to relevant text.

**Comment by BrunoVilela** [comment] 2015-08-31 05:04
I just pushed the fix for the number one

**Comment by BrunoVilela** [comment] 2015-08-31 05:14
The second I fixed now. I added a message when the user try to make the partition without masking first.

**Comment by BrunoVilela** [comment] 2015-08-31 05:19
I can't recreate here the errors 3 and 4... Bob, could you give the detailed sequence of the analysis until there?

**Comment by ndimhypervol** [comment] 2015-08-31 14:11
Hey guys -- the errors with ENMeval are definitely due to the fact that you're probably not using the ENMeval@edits version from github. This one has the updateProgress param that Wallace needs. Install this version via the commented code at the top of server.R and it should run fine.

**Comment by bobmuscarella** [comment] 2015-08-31 14:12
Great work, Bruno!  

For crash issues 3+4, this has to do with having a different version of ENMeval on my machine. (Jamie's right - I found that this morning and was in the middle of this comment...).  Re-installing ENMeval with:
`install_github("bobmuscarella/ENMeval@edits”)`
Seems fixed the problems.

A couple follow-ups on your fixes:
- Can you add text saying something like “Warning! “ to the message you put in the log for the 'Mask Predictors by Background' issue?  It would make it more clear that there is something wrong and that the user needs to do something.
- In the predicted suitability map (No threshold) the values on the map legend are all ‘-0’.  Is this a rounding problem where they are getting cut off or something?  ![See my screenshot linked here](https://github.com/bobmuscarella/Partitioning_and_Bioclim_in_ENMeval/blob/master/zerolegend.png)

**Comment by BrunoVilela** [comment] 2015-08-31 14:39
Warnings added

**Comment by ndimhypervol** [comment] 2015-09-03 02:26
Yeah Bob, that's due to the extremely low values of the raw output, I think, and the fact that the legend might internally be rounding. Bruno was looking into maybe listing the values in scientific notation -- any luck Bruno?

**Comment by BrunoVilela** [comment] 2015-09-03 02:39
The problem is due to the non-normalization of the values inside the enmval_edits package... the results output were very low... I add a normalization now... but as I said in the other issue, I want you to check if it OK.

**Comment by robertpanderson** [comment] 2015-09-03 12:19
Sorry to reply via regular email.

I think this “bug” is about the raw output of Maxent.  If so, here are my thoughts:

I don’t know what Bruno means by normalization. But the raw output of Maxent is scaled so that the probabilities sum to 1 for all of the pixels in the actual background sample used to build the model.  We *MUST* provide this in exactly that way, consistent with the literature.

Rob

*************************************
Robert P. Anderson, Ph.D.
Professor, Department of Biology
526 Marshak Science Building
City College of New York, City Univ. of New York
160 Convent Avenue
New York, NY 10031, USA

Telephone: (212) 650-8504
http://web.sci.ccny.cuny.edu/~anderson/
NOTE NEW E-MAIL: randerson@ccny.cuny.edu<mailto:randerson@ccny.cuny.edu>

**Comment by ndimhypervol** [comment] 2015-09-03 15:47
Yes, I removed the normalization so that the values are the same as the
normal raw output.

On 3 September 2015 at 08:19, robertpanderson <notifications@github.com>
wrote:

> Sorry to reply via regular email.
>
> I think this “bug” is about the raw output of Maxent. If so, here are my
> thoughts:
>
> I don’t know what Bruno means by normalization. But the raw output of
> Maxent is scaled so that the probabilities sum to 1 for all of the pixels
> in the actual background sample used to build the model. We *MUST* provide
> this in exactly that way, consistent with the literature.
>
> Rob
>
> *************************************
> Robert P. Anderson, Ph.D.
> Professor, Department of Biology
> 526 Marshak Science Building
> City College of New York, City Univ. of New York
> 160 Convent Avenue
> New York, NY 10031, USA
>
> Telephone: (212) 650-8504
> http://web.sci.ccny.cuny.edu/~anderson/
> NOTE NEW E-MAIL: randerson@ccny.cuny.edu<mailto:randerson@ccny.cuny.edu>
>
> From: Bruno Vilela de Moraes e Silva [mailto:notifications@github.com]
> Sent: Wednesday, September 02, 2015 10:40 PM
> To: ndimhypervol/wallace
> Subject: Re: [wallace] List of (?) Bugs! (#46)
>
>
> The problem is due to the non-normalization of the values inside the
> enmval_edits package... the results output were very low... I add a
> normalization now... but as I said in the other issue, I want you to check
> if it OK.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/ndimhypervol/wallace/issues/46#issuecomment-137305227>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/46#issuecomment-137420024>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Closed** 2016-01-06 22:06 UTC
